# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='avatar',
        ),
    ]
