# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180309_0723'),
        ('account', '0006_auto_20180309_1131'),
    ]

    operations = [
    ]
