# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20180309_1033'),
        ('account', '0007_merge_20180309_1351'),
    ]

    operations = [
    ]
