# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
